name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        targets: wasm32-wasip2

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install WASI SDK
      run: |
        wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-24/wasi-sdk-24.0-x86_64-linux.tar.gz
        tar xvf wasi-sdk-24.0-x86_64-linux.tar.gz
        sudo mv wasi-sdk-24.0-x86_64-linux /opt/wasi-sdk

    - name: Build project
      run: make web-build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web/dist
